import { useEffect, useState } from 'react';
import { apiRequest } from '../api';
import ErrorMessage from '../components/ErrorMessage';
import type { DashboardSummary, InventoryAlert } from '../types';

export default function AnalyticsPage() {
  const [summary, setSummary] = useState<DashboardSummary | null>(null); const [alerts, setAlerts] = useState<InventoryAlert[]>([]); const [error, setError] = useState<string | null>(null);
  async function load() { try { const [dashboard, inventoryAlerts] = await Promise.all([apiRequest<DashboardSummary>('/api/analytics/dashboard'), apiRequest<InventoryAlert[]>('/api/analytics/inventory-alerts')]); setSummary(dashboard); setAlerts(inventoryAlerts); setError(null); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No fue posible cargar la analítica.'); } }
  useEffect(() => { void load(); }, []);
  return <section className="overview"><div className="welcome-card"><div className="panel-heading"><div><p className="eyebrow">Fase 9</p><h2>Dashboard operacional</h2></div><button className="button" onClick={() => void load()}>Actualizar</button></div><p>Indicadores clínicos, farmacéuticos y de laboratorio consolidados en tiempo real.</p><ErrorMessage message={error} /></div>{summary && <div className="feature-grid"><article><span>{summary.activePatients}</span><strong>Pacientes activos</strong><small>Expedientes habilitados</small></article><article><span>{summary.appointmentsToday}</span><strong>Citas hoy</strong><small>Agenda del día</small></article><article><span>{summary.consultations30Days}</span><strong>Consultas 30 días</strong><small>Actividad clínica</small></article><article><span>{summary.activeMedications}</span><strong>Medicamentos</strong><small>Catálogo activo</small></article><article><span>{summary.lowStockLots}</span><strong>Stock bajo</strong><small>Lotes en reposición</small></article><article><span>{summary.expiringLots30Days}</span><strong>Próximos a vencer</strong><small>30 días</small></article><article><span>{summary.pendingLabOrders}</span><strong>Laboratorio pendiente</strong><small>Órdenes abiertas</small></article><article><span>{summary.completedLabOrders30Days}</span><strong>Resultados 30 días</strong><small>Órdenes completadas</small></article></div>}<section className="panel"><div className="panel-heading"><div><p className="eyebrow">Alertas</p><h2>Inventario que requiere atención</h2></div><span className="counter">{alerts.length}</span></div><div className="table-wrap"><table><thead><tr><th>Medicamento</th><th>Lote</th><th>Existencia</th><th>Vencimiento</th><th>Alerta</th></tr></thead><tbody>{alerts.map((a) => <tr key={a.lotId}><td><strong>{a.medicationName}</strong><small>{a.medicationCode}</small></td><td>{a.lotNumber}</td><td>{a.quantityOnHand} / mín. {a.reorderPoint}</td><td>{a.expirationDate}</td><td><span className="pill">{a.alertType === 'LOW_STOCK' ? 'Stock bajo' : 'Próximo a vencer'}</span></td></tr>)}</tbody></table></div></section></section>;
}
