import { FormEvent, useEffect, useState } from 'react';
import { apiRequest } from '../api';
import type { InventoryLot, InventoryMovement, Medication, StorageLocation } from '../types';
import ErrorMessage from '../components/ErrorMessage';

export default function InventoryPage({ canManage }: { canManage: boolean }) {
  const [lots, setLots] = useState<InventoryLot[]>([]); const [medications, setMedications] = useState<Medication[]>([]); const [locations, setLocations] = useState<StorageLocation[]>([]); const [kardex, setKardex] = useState<InventoryMovement[]>([]);
  const [selectedLot, setSelectedLot] = useState<string>(''); const [search, setSearch] = useState(''); const [error, setError] = useState<string | null>(null);
  const [lotForm, setLotForm] = useState({ medicationId: '', storageLocationId: '', lotNumber: '', expirationDate: '', unitCost: '0', initialQuantity: '0', reorderPoint: '0' });
  const [moveForm, setMoveForm] = useState({ type: 1, quantity: '1', reference: '', notes: '' });

  async function load() {
    try {
      const suffix = search ? `?search=${encodeURIComponent(search)}&lowStockOnly=false` : '?lowStockOnly=false';
      const [lotList, meds, locs] = await Promise.all([apiRequest<InventoryLot[]>(`/api/inventory/lots${suffix}`), apiRequest<Medication[]>('/api/pharmacy/medications?includeInactive=false'), apiRequest<StorageLocation[]>('/api/pharmacy/locations?includeInactive=false')]);
      setLots(lotList); setMedications(meds); setLocations(locs); setError(null);
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'No fue posible cargar el inventario.'); }
  }
  useEffect(() => { void load(); }, []);

  async function openKardex(id: string) { setSelectedLot(id); try { setKardex(await apiRequest<InventoryMovement[]>(`/api/inventory/lots/${id}/kardex`)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No fue posible cargar el kardex.'); } }
  async function createLot(event: FormEvent) { event.preventDefault(); try { await apiRequest('/api/inventory/lots', { method: 'POST', body: JSON.stringify({ ...lotForm, unitCost: Number(lotForm.unitCost), initialQuantity: Number(lotForm.initialQuantity), reorderPoint: Number(lotForm.reorderPoint) }) }); setLotForm({ medicationId: '', storageLocationId: '', lotNumber: '', expirationDate: '', unitCost: '0', initialQuantity: '0', reorderPoint: '0' }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No fue posible crear el lote.'); } }
  async function createMovement(event: FormEvent) { event.preventDefault(); if (!selectedLot) return; try { await apiRequest(`/api/inventory/lots/${selectedLot}/movements`, { method: 'POST', body: JSON.stringify({ type: moveForm.type, quantity: Number(moveForm.quantity), reference: moveForm.reference || null, notes: moveForm.notes || null }) }); setMoveForm({ type: 1, quantity: '1', reference: '', notes: '' }); await Promise.all([load(), openKardex(selectedLot)]); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No fue posible registrar el movimiento.'); } }

  return <div className="workspace-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Fase 7</p><h2>Inventario farmacéutico</h2></div><span className="counter">{lots.length}</span></div><div className="toolbar"><input placeholder="Medicamento, código o lote" value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') void load(); }} /><button className="button" onClick={() => void load()}>Buscar</button></div><ErrorMessage message={error} /><div className="table-wrap"><table><thead><tr><th>Medicamento</th><th>Lote</th><th>Ubicación</th><th>Existencia</th><th>Vence</th><th></th></tr></thead><tbody>{lots.map((lot) => <tr key={lot.id}><td><strong>{lot.medicationName}</strong><small>{lot.medicationCode}</small></td><td>{lot.lotNumber}</td><td>{lot.storageLocationName}</td><td><span className={lot.isLowStock ? 'pill pill--status-5' : 'pill'}>{lot.quantityOnHand}</span><small>mín. {lot.reorderPoint}</small></td><td>{lot.expirationDate}</td><td><button className="button button--small" onClick={() => void openKardex(lot.id)}>Kardex</button></td></tr>)}</tbody></table></div>{selectedLot && <div className="cards-list"><h3>Kardex</h3>{kardex.map((m) => <article className="appointment-card" key={m.id}><div><strong>{m.quantityDelta > 0 ? '+' : ''}{m.quantityDelta} unidades</strong><small>{m.reference || 'Movimiento de inventario'} · {m.performedBy}</small><time>{new Date(m.occurredAtUtc).toLocaleString('es-DO')}</time></div><span className="pill">Saldo {m.balanceAfter}</span></article>)}</div>}</section>
  <section className="panel panel--form"><p className="eyebrow">Control transaccional</p><h2>{canManage ? 'Lotes y movimientos' : 'Consulta de inventario'}</h2>{!canManage && <p className="muted">Tu rol tiene acceso de solo lectura.</p>}{canManage && <><form onSubmit={createLot} className="form-grid"><label className="form-span">Medicamento<select value={lotForm.medicationId} onChange={(e) => setLotForm({ ...lotForm, medicationId: e.target.value })} required><option value="">Seleccionar…</option>{medications.map((m) => <option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select></label><label>Ubicación<select value={lotForm.storageLocationId} onChange={(e) => setLotForm({ ...lotForm, storageLocationId: e.target.value })} required><option value="">Seleccionar…</option>{locations.map((l) => <option key={l.id} value={l.id}>{l.code} · {l.name}</option>)}</select></label><label>Lote<input value={lotForm.lotNumber} onChange={(e) => setLotForm({ ...lotForm, lotNumber: e.target.value })} required /></label><label>Vencimiento<input type="date" value={lotForm.expirationDate} onChange={(e) => setLotForm({ ...lotForm, expirationDate: e.target.value })} required /></label><label>Costo unitario<input type="number" min="0" step="0.01" value={lotForm.unitCost} onChange={(e) => setLotForm({ ...lotForm, unitCost: e.target.value })} /></label><label>Existencia inicial<input type="number" min="0" value={lotForm.initialQuantity} onChange={(e) => setLotForm({ ...lotForm, initialQuantity: e.target.value })} /></label><label>Punto de reposición<input type="number" min="0" value={lotForm.reorderPoint} onChange={(e) => setLotForm({ ...lotForm, reorderPoint: e.target.value })} /></label><button className="button button--primary form-span">Crear lote</button></form><hr />{selectedLot ? <form onSubmit={createMovement} className="form-grid"><label>Tipo<select value={moveForm.type} onChange={(e) => setMoveForm({ ...moveForm, type: Number(e.target.value) })}><option value={1}>Entrada</option><option value={2}>Dispensación</option><option value={3}>Ajuste +</option><option value={4}>Ajuste -</option></select></label><label>Cantidad<input type="number" min="1" value={moveForm.quantity} onChange={(e) => setMoveForm({ ...moveForm, quantity: e.target.value })} required /></label><label className="form-span">Referencia<input value={moveForm.reference} onChange={(e) => setMoveForm({ ...moveForm, reference: e.target.value })} /></label><label className="form-span">Notas<textarea value={moveForm.notes} onChange={(e) => setMoveForm({ ...moveForm, notes: e.target.value })} /></label><button className="button button--primary form-span">Registrar movimiento</button></form> : <p className="muted">Selecciona un lote para registrar movimientos y consultar su kardex.</p>}</>}</section></div>;
}
